# Generated by Django 4.0.3 on 2022-04-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_phone_number_alter_blog_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
